default_language_version:
  python: python

exclude : "migrations"
repos:
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [ '-iii', '-ll' ]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-bugbear",
          "flake8-comprehensions",
          "flake8-print",
          "flake8-simplify",
          "flake8-builtins",
        ]
