# Generated by Django 5.1.2 on 2024-10-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=100, verbose_name="Financial Accounts"),
                ),
                (
                    "account_type",
                    models.CharField(max_length=100, verbose_name="Account Type"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Account Balance"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("Dollar", "$"), ("Toman", "T")], max_length=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_name",
                    models.CharField(max_length=100, verbose_name="Goal Name"),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Target Amount"
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Current Amount"
                    ),
                ),
                ("due_date", models.DateField()),
                ("descrioption", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        max_length=7,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Amount of Transaction",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Daily Shopping", "Daily Shopping"),
                            ("Cafe and Restaurant", "Cafe and Restaurant"),
                            ("Commuting", "Commuting"),
                            ("House and Household", "House and Household"),
                            ("Beauty and Health", "Beauty and Health"),
                            ("Charge and Bill", "Charge and Bill"),
                            ("Fashion and Clothing", "Fashion and Clothing"),
                            ("Cultural and Artistic", "Cultural and Artistic"),
                            ("Fun and Entertainment", "Fun and Entertainment"),
                            ("Savings and Capital", "Savings and Capital"),
                            ("Exercise and Wellness", "Exercise and Wellness"),
                            ("Gift and Charity", "Gift and Charity"),
                            ("Loan Installments", "Loan Installments"),
                            ("Money Transfer", "Money Transfer"),
                            ("Cash Withdrawal", "Cash Withdrawal"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Transaction Category",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("descrioption", models.TextField()),
            ],
        ),
    ]
